#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${RED}APT${NC}"
apt-cache search $1
apt-cache policy $1

echo -e "${RED}\nSNAP${NC}"
snap search $1

echo -e "\n${RED}FLATPAK${NC}"
flatpak search $1