#!/bin/bash

RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${RED}APT${NC}"
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt autoremove

echo -e "\n${RED}SNAP${NC}"
sudo snap refresh

echo -e "\n${RED}FLATPAK${NC}"
flatpak update
